### ISSUE TITLE
claimDomain

### ISSUE THREAD

**Issue by ictg** [moderntld/.o#141]
ictg.o
?

**Comment by dannyhpy** [comment]
Hi! You can claim ictg.o by creating the `ictg` file in the **/zone** folder.
For instance, it can includes the following:

```
ictg  IN  CNAME  ictg.github.io.
```
Visitors of ictg.o will be redirected to ictg.github.io.

**Comment by ictg** [comment]
file wich the /zone folder?
ictg/.o/zone/
or in the
moderntld/.o/zone/

**Comment by dannyhpy** [comment]
Fork the repository, add the file in `/ictg/.o/zone` and create a pull request in **this repository**

**Comment by dannyhpy** [comment]
#143 is fine!

**Comment by ictg** [comment]
i did so.it is not working!

**Comment by dannyhpy** [comment]
Oh I see, this is not working due to the way GitHub Pages works. (this is the same issue as CloudFlare)
You probably want to specify an another domain/website instead.
