### ISSUE TITLE
ETA for merge to DNS Zone?

### ISSUE THREAD

**Issue by hackerpain** [moderntld/.o#162]
hey, when will #161 be rewiewed? thanks

cc @JonahAragon

**Comment by dannyhpy** [comment]
Looks this repository has been abandoned

**Comment by JonahAragon** [comment]
your zones are failing build checks, that should be investigated.

**Comment by hackerpain** [comment]
> Your zones are failing build checks, that should be investigated (they also use duplicate nameservers...)
> 
> Also, the goal is really for active use and not domain parking, so I'm not sure what you are trying to accomplish with hundreds of domains but it seems antithetical to the goals of OpenNIC.

Yes, indeed, i was trying to park them for future sales. 👍 good luck with your mission!
