### ISSUE TITLE
Registered domains doesn't work on whois command.

### ISSUE THREAD

**Issue by yhk1038** [moderntld/.o#51]
I'm checking seriously to using this `.o` first class dns. But any of registered domain in `/zone` directory don't respond when i use whois command like this:

```bash
$ whois example.o
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 0 objects.
%
% You queried for example.o but this server does not have
% any data for example.o.
%
% If you need further information please check the web site
% or use -h for help

$
```

Is there any problem for using Top-level DNS `.o` ? or Can i check with any other method?

**Comment by samip5** [comment]
This top level domain, does not have any information stored at IANA or anywhere else for that matter to my knowledge.

**Comment by JonahAragon** [comment]
@samip5 is correct, this is expected behavior. If you have any questions about how OpenNIC operates check out https://www.opennic.org/ and [their mailing list](https://wiki.opennic.org/opennic/mailinglist).
